M48
; DRILL file {KiCad 8.0.4} date 2024-09-03T13:17:27-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-03T13:17:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X5.0984Y-4.2126
X5.748Y-4.2126
T2
X5.448Y-3.5827
X5.748Y-3.5827
T3
X5.0984Y-3.5827
X5.1984Y-3.5827
M30
